######################################################################
# Automatically generated by qmake (2.01a) Wed Jul 24 10:27:40 2013
######################################################################

TEMPLATE	= app
TARGET		= configure-sw
QT		+= widgets
DEPENDPATH	+= .
INCLUDEPATH	+= .

win32 	{
DESTDIR	= ../../../windows-bin-sw
}

unix	{
DESTDIR = ../../linux-bin
}

# Input
HEADERS += configurator.h
FORMS += configurator.ui
SOURCES += configurator.cpp main.cpp
